### ISSUE TITLE
Visualizer keeps flashing

### ISSUE THREAD

**Issue by instr3** [chirs241097/QMidiPlayer#12]
_The visualizer made my dog eye blind_

Environment:
Windows 10 x64

Version:
Latest released version

How to reproduce it:

1) Run QMidiPlayer
2) Open the visualizer (can either do with song playing or no song playing)
3) The visualizer keeps flashing, alternating between a 1-frame white screen (screenshot below) and 1-frame piano roll (screenshot below)

![image](https://user-images.githubusercontent.com/13694510/98440085-6c5bc600-2131-11eb-961b-fc8d554225ea.png)

![image](https://user-images.githubusercontent.com/13694510/98440060-551cd880-2131-11eb-897d-72fe5d85b667.png)

**Comment by instr3** [comment]
Solved by setting MSAA to 1 (default value: 0)

Thanks to @chirs241097

**Comment by chirs241097** [comment]
This is a known issue. As a temporary workaround, use the 2D visualization, or set MSAA to a value greater than 0.

If possible, please post your display driver information to help me investigate this issue.
