### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [chirs241097/QMidiPlayer#7]
Hi @chirs241097 . I'm a graphic designer. I wanted to contribute to your project and I've designed a logo for your project. If you like it, you can use it. it's free. I'll send you files and pr. tell me if you need anything change i'll fix it. 
Best Reagard
![qmidi](https://user-images.githubusercontent.com/36124339/42413544-f5f7c624-824c-11e8-97a3-c9b12f11c2dd.png)

**Comment by chirs241097** [comment]
That's very nice of you. Unfortunately we don't think this project is in a desperate need of a new logo. Thanks for your interest in this project anyway.

Chris Xiong
