### ISSUE TITLE
Feature: Convert to WAV

### ISSUE THREAD

**Issue by Sembiance** [chirs241097/QMidiPlayer#9]
Greetings

I'd love to be able to use QMidiPlayer to convert a given file into a WAV from the console. Basically I have some old .MDS files that QMidiPlayer plays great, but I just want to do a `qmidiplayer input.mds output.wav`

It would be even more awesome to convert mds to mid but WAV sounds easier.

I'm a coder, so I'd be happy to add this feature in and send a pull request. Any tips on which .cpp files have the code I need to do this?

**Comment by Sembiance** [comment]
Nevermind, I ended up just writing a quick program to do it using this code: https://github.com/kode54/midi_processing

Thanks!

**Comment by chirs241097** [comment]
Glad to hear you have found a solution. In fact, I learned about the MDS format by reading the code you mentioned above.

Unfortunately the part that needs to be changed to implement this feature in QMidiPlayer is still quite a mess, plus the focus of this project is to provide a GUI-based midi player. Therefore I'm probably not going to add the requested feature as it was requested. However, adding batch conversion of the entire playlist to the GUI sounds like a good idea.

For CLI usage, my recommendation remains unchanged: use the command line utility provided by fluidsynth instead.
